# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 17:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[(b'1', b'Clientes'), (b'2', b'Pc'), (b'3', b'Telefono'), (b'4', b'Peticiones'), (b'5', b'Peticiones Completadas'), (b'6', b'Peticiones Entregadas'), (b'7', b'Usuarios')], max_length=2, null=True)),
                ('object_id', models.BigIntegerField()),
                ('accion', models.CharField(blank=True, choices=[(b'1', b'Crear'), (b'2', b'Modificar'), (b'3', b'Elimina')], max_length=2, null=True)),
                ('descripcion', models.TextField()),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bitacora',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='Hermanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('sexo', models.CharField(blank=True, choices=[(b'1', b'Masculino'), (b'2', b'Femenino')], max_length=2, null=True)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hermanos',
            },
        ),
        migrations.CreateModel(
            name='Ministerios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ministerios',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=50)),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermanos.Hermanos')),
            ],
            options={
                'db_table': 'telefono',
            },
        ),
        migrations.AddField(
            model_name='hermanos',
            name='ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hermanos.Ministerios'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='hermano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermanos.Hermanos'),
        ),
    ]
