# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hermanos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.TimeField()),
                ('Direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Direccion', to='hermanos.Hermanos')),
                ('coros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coros', to='hermanos.Hermanos')),
                ('lectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectura', to='hermanos.Hermanos')),
                ('oracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oracion', to='hermanos.Hermanos')),
                ('predicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicacion', to='hermanos.Hermanos')),
                ('recolecion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recolecion', to='hermanos.Hermanos')),
            ],
            options={
                'db_table': 'cultos',
            },
        ),
    ]
