# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hermanos', '0001_initial'),
        ('culto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('hora', models.TimeField()),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermanos.Hermanos')),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
    ]
