# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culto', '0002_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultos',
            name='fecha',
            field=models.DateField(),
        ),
    ]
