# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culto', '0003_auto_20160513_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeCulto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tipos_de_cultos',
            },
        ),
        migrations.AddField(
            model_name='cultos',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='culto.TipoDeCulto'),
            preserve_default=False,
        ),
    ]
