# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0001_initial'),
        ('hermanos', '0002_hermanos_user'),
        ('culto', '0004_auto_20160513_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField()),
                ('culto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culto.Cultos')),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermanos.Hermanos')),
            ],
            options={
                'db_table': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='EstadoDelCulto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versiculos', models.BooleanField(default=False)),
                ('invitacion', models.BooleanField(default=False)),
                ('anuncio', models.BooleanField(default=False)),
                ('coros', models.BooleanField(default=False)),
                ('culto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='culto.Cultos')),
            ],
            options={
                'db_table': 'estado_del_culto',
            },
        ),
        migrations.CreateModel(
            name='IvitacionDelCulto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Direccion', models.BooleanField(default=False)),
                ('lectura', models.BooleanField(default=False)),
                ('recolecion', models.BooleanField(default=False)),
                ('oracion', models.BooleanField(default=False)),
                ('coros', models.BooleanField(default=False)),
                ('predicacion', models.BooleanField(default=False)),
                ('culto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='culto.Cultos')),
            ],
            options={
                'db_table': 'invitacion_del_culto',
            },
        ),
        migrations.CreateModel(
            name='VersiculoDelCulto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.PositiveIntegerField()),
                ('desde', models.PositiveIntegerField()),
                ('hasta', models.PositiveIntegerField()),
                ('culto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='culto.Cultos')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblia.Libros')),
            ],
            options={
                'db_table': 'versiculo_del_culto',
            },
        ),
    ]
