# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culto', '0005_comentarios_estadodelculto_ivitaciondelculto_versiculodelculto'),
    ]

    operations = [
        migrations.AddField(
            model_name='versiculodelculto',
            name='selecionado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
