# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culto', '0006_versiculodelculto_selecionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versiculodelculto',
            name='selecionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblia.Versiculos'),
        ),
    ]
