# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culto', '0007_auto_20160520_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='versiculodelculto',
            name='todos',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
