# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 19:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('culto', '0008_versiculodelculto_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivitaciondelculto',
            name='fecha_modificado',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 20, 19, 18, 11, 864358, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versiculodelculto',
            name='fecha_modificado',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 20, 19, 18, 26, 168016, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
