# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culto', '0011_cultos_escuela_de_nino'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivitaciondelculto',
            name='escuela_de_nino',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ivitaciondelculto',
            name='escuela_dominical',
            field=models.BooleanField(default=False),
        ),
    ]
