# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='capitulos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
